### ISSUE TITLE
testing on linux

### ISSUE THREAD

**Issue by epifanio** [haruiz/CvStudio#12]
Hi, I was trying out this new app (Thanks!) on a Linux environment, using the system python that ships with it.

I only modified the [pip_req.txt](https://github.com/haruiz/CvStudio/blob/master/pip_req.txt) by removing the forced versions for some of the dependencies (so to don't replace libraries I already have installed) I then make sure I had the other dependencies (torch etc.) were installed correctly.

My pipreq.txt looks like:

```
certifi==2019.6.16
cffi==1.12.3
dask
hurry.filesize==0.9
imutils==0.5.3
more-itertools==7.2.0
numpy==1.17.2
olefile==0.46
opencv-contrib-python
peewee==3.10.0
Pillow
pycparser==2.19
pyface==6.1.2
PyQt5
PyQt5
#PyQt5Designer
six==1.12.0
toolz==0.10.0
traits==5.1.2
wincertstore==0.2
marshmallow==3.2.0
```
Note I didn't find a package for `PyQt5Designer`

```
epinux@epinux:~$ pip3 install PyQt5Designer
ERROR: Could not find a version that satisfies the requirement PyQt5Designer (from versions: none)
ERROR: No matching distribution found for PyQt5Designer
epinux@epinux:~$ pip3 install PyQt5Designer==5.10.1
ERROR: Could not find a version that satisfies the requirement PyQt5Designer==5.10.1 (from versions: none)
ERROR: No matching distribution found for PyQt5Designer==5.10.1
epinux@epinux:~$ 
```

Tring to run the app I noticed some differences from the video, in my case there are no "menu-actions" in the lower-left side of the application toolbar, and I was not able to understand how load images into the app. Here a quick record of my desktop trying to run the app:  https://epinux.com/index.php/s/5TTQSDw6Y79DHYK 

Do you have any hints on how to debug this issue?

I don't know if useful, but from trying to click on some of the links below the dataset folder icon, I got the following error log:

```
python3 cvstudio.py 
libpng warning: iCCP: known incorrect sRGB profile
AttributeError: __getattribute__

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/epinux/PycharmProjects/CvStudio/view/widgets/tab_datasets.py", line 177, in open_dataset_action_slot
    tab_widget = MediaTabWidget(vo)
  File "/home/epinux/PycharmProjects/CvStudio/view/widgets/tab_media.py", line 21, in __init__
    self.media_grid=Gallery()
  File "/home/epinux/PycharmProjects/CvStudio/view/widgets/gallery/gallery.py", line 119, in __init__
    self.setupUi(self)
  File "/home/epinux/PycharmProjects/CvStudio/view/widgets/gallery/base_gallery.py", line 221, in setupUi
    QtCore.QMetaObject.connectSlotsByName(Gallery)
SystemError: <built-in function connectSlotsByName> returned a result with an error set
AttributeError: __getattribute__

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/epinux/PycharmProjects/CvStudio/view/widgets/tab_datasets.py", line 177, in open_dataset_action_slot
    tab_widget = MediaTabWidget(vo)
  File "/home/epinux/PycharmProjects/CvStudio/view/widgets/tab_media.py", line 21, in __init__
    self.media_grid=Gallery()
  File "/home/epinux/PycharmProjects/CvStudio/view/widgets/gallery/gallery.py", line 119, in __init__
    self.setupUi(self)
  File "/home/epinux/PycharmProjects/CvStudio/view/widgets/gallery/base_gallery.py", line 221, in setupUi
    QtCore.QMetaObject.connectSlotsByName(Gallery)
SystemError: <built-in function connectSlotsByName> returned a result with an error set
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
```

**Comment by haruiz** [comment]
Hi @epifanio, thanks for report the issue,  I'll try to reproduce your environment and see if iI could get the same error, I suspect could be the version of the pyqt5, anyways I'll follow your instructions. keep in touch

**Comment by epifanio** [comment]
Thanks @haruiz, 
below a quick report about the Qt and PyQt version:

```python
In [1]: from PyQt5.QtCore import QT_VERSION_STR 
   ...: from PyQt5.Qt import PYQT_VERSION_STR 
   ...: from sip import SIP_VERSION_STR 
   ...:  
   ...: print("Qt version:", QT_VERSION_STR) 
   ...: print("SIP version:", SIP_VERSION_STR) 
   ...: print("PyQt version:", PYQT_VERSION_STR)                                                                                                                                        
Qt version: 5.12.4
SIP version: 4.19.18
PyQt version: 5.12.3
``` 
I am using `Python3` on `Ubuntu-19.10`

```python
In [2]: import sys                                                                                                                                                                      

In [3]: sys.executable                                                                                                                                                                  
Out[3]: '/usr/bin/python3'

In [4]: sys.version                                                                                                                                                                     
Out[4]: '3.7.5rc1 (default, Oct  8 2019, 16:47:45) \n[GCC 9.2.1 20191008]'

In [5]: !uname -a                                                                                                                                                                      
Linux epinux 5.3.0-19-generic #20-Ubuntu SMP Fri Oct 18 09:04:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by haruiz** [comment]
Hi, @epifanio I tried to replicate your environment and run the software on Linux. It worked without problems, attached I am sending you the pip_req.txt with the packages that I used,  and a video where you can see the software running, try again, and let me know if you still have the same problem.
[pip_req.txt](https://github.com/haruiz/CvStudio/files/3802675/pip_req.txt)
https://youtu.be/dYvuarGWXiI
